config/routes.rb
Lastcall::Application.routes.draw do
  root 'search#index', as: '/'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions 
  resources :search

  get "search_products", to: "search#search_products"
  
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations: false)
  validates_uniqueness_of :email
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true

  # Custom Password validations
  validates :password, presence: true, length: { minimum: 6 }, on: :create, if: :not_using_omniauth
  validates_presence_of :password_confirmation, if: lambda { |m| m.password.present? }
  validates_confirmation_of :password, if: lambda { |m| m.password.present? }

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  private

  def not_using_omniauth
    oauth_token.nil?
  end
end

app/models/watchlist.rb
class Watchlist < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
before_action :set_search, only: [:show, :edit, :update, :destroy]

  def search_products
    encoded = URI.encode(params[:search_id])
    response = HTTParty.get("http://api.shopstyle.com/api/v2/products?pid=uid6096-24223436-93&fts=#{encoded}&limit=20&sort=Popularity&fl=d0&fl=d101")
    render json: response
  end

  def create
    # binding.pry
    @search = Search.new(search_params)
    if @search.save
      render json: @search
    else
      render json: @search.errors, status: :unprocessable_entity
    end
  end

  def update
   if @search.update
      head :no_content
    else
      render json: @search.errors, status: :unprocessable_entity
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_search
    @search = Search.find(params[:name])
  end  

  def search_params

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def new
    if logged_in?
      redirect_to search_index_path
    end
  end

  def create
    auth = User.from_omniauth(env["omniauth.auth"])
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to login_path, notice: "Logged in!"
    elsif auth
      session[:user_id] = auth.id
      redirect_to login_path, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticated!, :set_user, :authorized!, except: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show
    render :edit
  end
  
  def destroy
    if @user.destroy
      redirect_to new_user_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authorized!
    unless @user.id == session[:user_id]
      redirect_to user_path(session[:user_id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:user_id].present?
  end

  def authenticated!
    unless logged_in?
      redirect to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Last Call</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
  <div id="user_header">
   <% if logged_in? %>
   <span> Last Call </span>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log Out", logout_path %>
    <%= link_to "Edit Profile", edit_user_path(current_user) %>
  <% end %>
  <% if !logged_in? %>
    <span> Last Call </span>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
  </div>
</div>

<%= yield %>

<%= javascript_include_tag 'application' %>

</body>
</html>

app/views/search/index.html.erb
<form class="search">
    <input type="text" name="title" placeholder="Enter Keyword">
    <button>Submit</button>
</form>

 <h1 class="sale">Now on sale:</h1>
<script type="text/html" class="search-result"> 
  <h3><%%= this.model.get("name") + "  " + this.model.get("salePriceLabel") %> <span><%%= " (" + Math.round(((this.model.get("price") - this.model.get("salePrice")) / this.model.get("price")) * 100) + "% OFF)" %></span>
  
  <span>
  <%% if (this.model.get("added")) { %>
  <button type="button" class="add" disabled>Added!</button>
  <%% } else { %>
  <button type="button" class="add">Add to Watch List</button>
  <%% } %>

  <a href= "<%%= this.model.get("pageUrl") %>" target="_blank"><img src=" <%%= this.model.get("image").sizes.Original.url %>"  class="image" />
  </a>
  </span></h3>

</script>

app/views/users/_form.html.erb
  <% unless @user.errors.none? %>
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>


<%= form_for @user do |f| %>
  <p><%= f.text_field :name, :placeholder => "Name"%></p>
  <p><%= f.email_field :email, :placeholder => "Email"%></p>
  <p><%= f.password_field :password, :placeholder => "Password" %></p> 
  <p><%= f.password_field :password_confirmation, :placeholder => "Password" %></p>
  <p><%= f.text_field :phone, :placeholder => "Phone Number" %></p>
  <p><%= f.hidden_field :id, value: "#{session[:user_id]}" %></p>
  <p class = "submit"> <%= f.submit %> </p>
<% end %>

app/views/users/edit.html.erb
<h1>Editing <%= @user.email %></h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>